// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'footer': string;
  'form': string;
  'login-btn': string;
  'site-form-item-icon': string;
}
export const cssExports: CssExports;
export default cssExports;
