// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card': string;
  'gray': string;
  'home': string;
  'images': string;
  'number': string;
  'text': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
