// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content-wrapper': string;
  'tool-wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
